config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  post 'pages/update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/nft.rb
class Nft < ApplicationRecord
  def self.find_two_unique
    [
      Nft.order(Arel.sql('RANDOM()')).first,
      Nft.order(Arel.sql('RANDOM()')).last
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    assign_nfts
  end

  def update
    nft = Nft.find(params[:id])
    nft.update!(vote_count: nft.vote_count + 1)

    assign_nfts
  end

  private

  def assign_nfts
    @nft1, @nft2 = Nft.find_two_unique
    @leaderboard_nfts = Nft.order(vote_count: :desc).limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NFT Book</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-10 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="text-4xl font-extrabold mb-4 text-center">NFT Book</h1>

<div class="grid grid-cols-2 w-3/4 mx-auto">
  <%= render 'pages/home/leaderboard', records: @leaderboard_nfts %>

  <%= render 'pages/home/faceoff',
      nft1: @nft1,
      nft2: @nft2
  %>
</div>

app/views/pages/home/_faceoff.html.erb
<div id="faceoff" class="grid grid-cols-2">
  <div>
    <div class="mb-3">
      <%= nft1.name %>
    </div>

    <%= form_tag(pages_update_path) do %>
      <%= hidden_field_tag 'id', nft1.id %>
      <button class="bg-blue-600 text-white px-4 py-2">Vote</button>
    <% end %>
  </div>

  <div>
    <div class="mb-3">
      <%= nft2.name %>
    </div>

    <%= form_tag(pages_update_path) do %>
      <%= hidden_field_tag 'id', nft2.id %>
      <button class="bg-blue-600 text-white px-4 py-2">Vote</button>
    <% end %>
  </div>
</div>

app/views/pages/home/_leaderboard.html.erb
<div id="leaderboard">
  <% records.each do |record| %>
    <div>
      <%= record.name %>: <%= record.vote_count %>
    </div>
  <% end %>
</div>

app/views/pages/update.turbo_stream.erb
<%= turbo_stream.replace 'leaderboard' do %>
  <%= render 'pages/home/leaderboard',
      records: @leaderboard_nfts
  %>
<% end %>

<%= turbo_stream.replace 'faceoff' do %>
  <%= render 'pages/home/faceoff',
      nft1: @nft1,
      nft2: @nft2
  %>
<% end %>